// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NetworkDNSLookup(arg1) {
  return window['go']['main']['App']['NetworkDNSLookup'](arg1);
}

export function NetworkGetSystemDNSServers() {
  return window['go']['main']['App']['NetworkGetSystemDNSServers']();
}

export function NetworkPing(arg1, arg2, arg3) {
  return window['go']['main']['App']['NetworkPing'](arg1, arg2, arg3);
}

export function NetworkStartSpeedTest(arg1) {
  return window['go']['main']['App']['NetworkStartSpeedTest'](arg1);
}

export function NetworkStopPing() {
  return window['go']['main']['App']['NetworkStopPing']();
}

export function NetworkStopSpeedTest() {
  return window['go']['main']['App']['NetworkStopSpeedTest']();
}
