// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function Greet(arg1:string):Promise<string>;

export function NetworkDNSLookup(arg1:string):Promise<network.DNSResult>;

export function NetworkGetSystemDNSServers():Promise<Array<string>>;

export function NetworkPing(arg1:string,arg2:number,arg3:number):Promise<network.PingResult>;

export function NetworkStartSpeedTest(arg1:network.SpeedTestConfig):Promise<void>;

export function NetworkStopPing():Promise<void>;

export function NetworkStopSpeedTest():Promise<void>;
